# This workflow will test on Bun lastest stable major
name: Bun CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ› ï¸ Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest # the lastest Bun version

      - name: ğŸ“¦ Install dependencies
        run: bun install

      - name: ğŸ§ª Run tests
        run: bun test  --ignore-pattern "deno/**"
